In [1]:
import pandas as pd
import joblib

In [2]:
model = joblib.load("weather_model.pkl")

print("Model Loaded Successfully")

Model Loaded Successfully

In [4]:
test_df = pd.read_csv("test.csv")

test_df.head()

,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Temperature (C)
0,0.53,13.3469,304.0,15.5526,1014.03,28.122222
1,0.83,14.4900,150.0,9.9820,1017.90,10.000000
2,0.65,11.0446,144.0,9.6278,1022.00,14.400000
3,0.85,12.8156,40.0,8.0500,999.83,1.016667
4,0.82,7.4221,98.0,7.5509,1037.03,-0.122222

In [5]:
X_batch = test_df.drop("Temperature (C)", axis=1)

print(X_batch.shape)

(19291, 5)

In [6]:
predictions = model.predict(X_batch)

print("Predictions Generated")

Predictions Generated

In [7]:
results = pd.DataFrame({
    "Actual": test_df["Temperature (C)"],
    "Predicted": predictions
})

results.head(20)

       Actual  Predicted
0   28.122222  16.670722
1   10.000000   4.409222
2   14.400000   9.889500
3    1.016667   4.244389
4   -0.122222  -0.659500
5    2.022222   6.412611
6   26.111111  23.579722
7   16.016667  13.084000
8    9.888889   4.636889
9    8.383333   8.507000
10   1.033333   3.710722
11  18.650000  10.780167
12  -6.111111   0.830778
13  14.005556   6.395222
14  27.800000  21.446889
15  11.755556   9.686667
16   7.750000   6.797389
17  22.644444  12.478000
18   4.211111   2.294944
19  17.777778  13.337500

In [8]:
results.to_csv("predictions.csv", index=False)

print("predictions.csv saved")

predictions.csv saved

In [9]:
print("Total Predictions:", len(results))

print("\nPrediction Summary")
print(results.describe())

Total Predictions: 19291

Prediction Summary
             Actual     Predicted
count  19291.000000  19291.000000
mean      11.885618     11.797353
std        9.600211      7.920025
min      -19.166667    -18.238389
25%        4.461111      6.042194
50%       11.727778     11.306444
75%       18.883333     17.029833
max       38.838889     38.662778